import fs from 'fs'
import matter from 'gray-matter'
import Link from 'next/link'
import path from 'path'
import { contentFilePaths, CONTENT_PATH } from '../utils/mdxUtils'

export default function Index({ chapters }) {
  return (
    <>
      <h1>Home Page</h1>
      <p>
        Click the link below to navigate to a page generated by{' '}
        <code>next-mdx-remote</code>.
      </p>
      <ul>
        {chapters.map((chapter) => (
          <li key={chapter.filePath}>
            <Link href={`/${chapter.filePath.replace(/\.mdx?$/, '')}`}>
              <a>
                {chapter.data.title} ({chapter.data.part})
              </a>
            </Link>
          </li>
        ))}
      </ul>
    </>
  )
}

export function getStaticProps() {
  const chapters = contentFilePaths.map((filePath) => {
    const source = fs.readFileSync(path.join(CONTENT_PATH, filePath))
    const { content, data } = matter(source)

    return {
      content,
      data,
      filePath
    }
  })

  return { props: { chapters: chapters } }
}
